---
key: "Badges_Pack_1"
price_currency: "crypt"
price: "25"
reward_currency: "badges"
reward: "125"
---
key: "Badges_Pack_2"
price_currency: "crypt"
price: "100"
reward_currency: "badges"
reward: "500"
---
key: "Badges_Pack_3"
price_currency: "crypt"
price: "250"
reward_currency: "badges"
reward: "1250"
---
key: "Badges_Pack_4"
price_currency: "crypt"
price: "350"
reward_currency: "badges"
reward: "1750"
---
key: "Bucks_Pack_1"
price_currency: "crypt"
price: "25"
reward_currency: "bucks"
reward: "125"
---
key: "Bucks_Pack_2"
price_currency: "crypt"
price: "100"
reward_currency: "bucks"
reward: "500"
---
key: "Bucks_Pack_3"
price_currency: "crypt"
price: "250"
reward_currency: "bucks"
reward: "1250"
---
key: "Bucks_Pack_4"
price_currency: "crypt"
price: "350"
reward_currency: "bucks"
reward: "1750"
