---
key: "badges"
initial_amount: 4000
---
key: "bucks"
initial_amount: 0
---
key: "crypt"
initial_amount: 0
---
key: "rating"
initial_amount: 150
min_amount: 0
allow_negative_additions: true
---
key: "loadout_tickets"
initial_amount: 0
