---
key: "item_backpack_common"
item: "item_backpack_common"
---
key: "item_perk_speedUp"
item: "item_perk_speedUp"
---
key: "item_healBox_small"
item: "item_healBox_small"
---
key: "item_healBox_big"
item: "item_healBox_big"
---
key: "item_ammoBox_rifle_common"
item: "item_ammoBox_rifle_common"
---
key: "item_ammoBox_pistol_common"
item: "item_ammoBox_pistol_common"
---
key: "item_ammoBox_shotgun_common"
item: "item_ammoBox_shotgun_common"
---
key: "item_ability_grenade"
item: "item_ability_grenade"
---
key: "item_skin_default"
item: "item_skin_default"
---
key: "item_armor_light_common"
item: "item_armor_light_common"
---
key: "item_helmet_light_common"
item: "item_helmet_light_common"
---
key: "item_attachment_compensator_common"
item: "item_attachment_compensator_common"
---
key: "item_attachment_silencer_common"
item: "item_attachment_silencer_common"
---
key: "item_attachment_scope_common"
item: "item_attachment_scope_common"
