---
key: "lvl_1"
level: 1
exp_to_next_level: 100
---
key: "lvl_2"
level: 2
exp_to_next_level: 350
---
key: "lvl_3"
level: 3
exp_to_next_level: 630
---
key: "lvl_4"
level: 4
exp_to_next_level: 800
---
key: "lvl_5"
level: 5
exp_to_next_level: 1080
---
key: "lvl_6"
level: 6
exp_to_next_level: 1107
---
key: "lvl_7"
level: 7
exp_to_next_level: 1476
---
key: "lvl_8"
level: 8
exp_to_next_level: 1845
---
key: "lvl_9"
level: 9
exp_to_next_level: 2430
---
key: "lvl_10"
level: 10
exp_to_next_level: 2835
---
key: "lvl_11"
level: 11
exp_to_next_level: 3645
---
key: "lvl_12"
level: 12
exp_to_next_level: 5400
---
key: "lvl_13"
level: 13
exp_to_next_level: 6750
---
key: "lvl_14"
level: 14
exp_to_next_level: 8100
---
key: "lvl_15"
level: 15
exp_to_next_level: 10350
---
key: "lvl_16"
level: 16
exp_to_next_level: 15921
---
key: "lvl_17"
level: 17
exp_to_next_level: 20313
---
key: "lvl_18"
level: 18
exp_to_next_level: 31050
---
key: "lvl_19"
level: 19
exp_to_next_level: 39825
---
key: "lvl_20"
level: 20
exp_to_next_level: 70000
