---
key: "Crypt_Pack_1"
android_id: "crypt_pack_1"
ios_id: "crypt_pack_1"
type: "Consumable"
price_usd_cents: 200
---
key: "Crypt_Pack_2"
android_id: "crypt_pack_2"
ios_id: "crypt_pack_2"
type: "Consumable"
price_usd_cents: 500
---
key: "Crypt_Pack_3"
android_id: "crypt_pack_3"
ios_id: "crypt_pack_3"
type: "Consumable"
price_usd_cents: 1000
---
key: "Crypt_Pack_4"
android_id: "crypt_pack_4"
ios_id: "crypt_pack_4"
type: "Consumable"
price_usd_cents: 2500
