---
key: "quest_donate_weapons__donate_ak74"
quest: "quest_donate_weapons"
item_setup: "item_weapon_AR_common_muzzleCommon"
---
key: "quest_donate_weapons__donate_pistol"
quest: "quest_donate_weapons"
item_setup: "item_weapon_pistol_common"
